# Wormhole addition: mirrors canton/bob/app-auth.conf.
canton.participants.guardian-observer {
  ledger-api {
    auth-services = [{
      type = unsafe-jwt-hmac-256
      target-audience = "https://canton.network.global"
      secret = "unsafe"
    }]

    user-management-service.additional-admin-user-id = ledger-api-user
  }
}
