# Wormhole addition: the "guardian-observer" Canton participant -- see canton/bob/app.conf
# for the pattern this mirrors.
canton.participants.guardian-observer = ${_participant} {
  storage.config.properties.databaseName = participant-guardian-observer
  monitoring {
    http-health-server.port = 7900
    grpc-health-server.port = 7961
  }
  http-ledger-api.port = 7975
  admin-api.port = 7902
  ledger-api.port = 7901
}
