// Command vaagen is a small, checked-in fixture generator: it prints the
// AcceptAdminTransferByVaa governance-VAA fixtures embedded (as pinned hex
// constants) in canton/test/daml/Test/TestNtt.daml's accept-admin-by-VAA test
// section. It exists so those fixtures have a reproducible, auditable
// provenance (this command), rather than being hand-computed or generated by a
// one-off script.
//
// Every fixture is signed by the standard devnet guardian key
// (cfb12303a19cde580bb4dd771639b0d26bc68353645571a8cff516ab2ee113a0, set 0,
// guardian index 0), with the standard governance emitter (chain 1, address
// 0x00..04, matching Test.TestCore:govSetFeeVAA) unless a fixture specifically
// exercises the emitter check. Timestamp and nonce are arbitrary but fixed so
// output is stable across runs; only the sequence and the field(s) each
// fixture targets vary.
//
// Regenerate with:
//
//	go run ./cmd/vaagen
package main

import (
	"encoding/binary"
	"encoding/hex"
	"fmt"

	"github.com/wormholelabs-xyz/native-token-transfers/canton/testing/cli/internal/guardian"
)

const devnetGuardianKeyHex = "cfb12303a19cde580bb4dd771639b0d26bc68353645571a8cff516ab2ee113a0"

// fixedTimestamp is an arbitrary-but-fixed VAA timestamp shared by every
// fixture, so regenerating this command's output is byte-for-byte stable.
const fixedTimestamp = 1700000000

const cantonChain = 72

// b32 returns a 32-byte value whose last byte is last, matching Daml's
// `b32 "hh"` (Test.TestNtt's `leftPadTo 32`) and the Go integration harness's
// b32Match.
func b32(last byte) [32]byte {
	var b [32]byte
	b[31] = last
	return b
}

var (
	managerAA = b32(0xaa)
	managerAB = b32(0xab)
)

// coreModulePadded is ASCII "Core" left-padded to 32 bytes -- the wrongModule
// fixture's (deliberately wrong) module field, matching
// Wormhole.Core.Governance:coreModule.
var coreModulePadded = func() [32]byte {
	var m [32]byte
	copy(m[32-4:], []byte("Core"))
	return m
}()

// rawAcceptAdminPayload builds the NTT AcceptAdminTransferToGovernance payload
// by hand -- module(32) || action(1) || chain(2) || managerAddress(32) ||
// factoryEpoch(8) -- without going through guardian.SignAcceptAdmin, which
// always emits the CORRECT module/action. Used to build the wrongModule and
// wrongAction negative fixtures.
func rawAcceptAdminPayload(module [32]byte, action byte, chain uint16, managerAddress [32]byte, factoryEpoch uint64) []byte {
	payload := make([]byte, 0, 32+1+2+32+8)
	payload = append(payload, module[:]...)
	payload = append(payload, action)
	chainBytes := make([]byte, 2)
	binary.BigEndian.PutUint16(chainBytes, chain)
	payload = append(payload, chainBytes...)
	payload = append(payload, managerAddress[:]...)
	epochBytes := make([]byte, 8)
	binary.BigEndian.PutUint64(epochBytes, factoryEpoch)
	payload = append(payload, epochBytes...)
	return payload
}

// baseParams is the shared VAA envelope every fixture starts from: fixed
// timestamp, the standard governance emitter (chain 1, 0x00..04), the given
// sequence (distinct per fixture so digests never collide), consistencyLevel 0
// -- matching Test.TestCore:govSetFeeVAA.
func baseParams(seq uint64) guardian.GovernanceParams {
	return guardian.GovernanceParams{
		Timestamp:      fixedTimestamp,
		Sequence:       seq,
		EmitterChain:   guardian.DefaultGovernanceChain,
		EmitterAddress: guardian.DefaultGovernanceAddress,
	}
}

func signRaw(key *guardian.Key, p guardian.GovernanceParams, payload []byte) []byte {
	vaa, err := guardian.Sign(key, guardian.VAAParams{
		Timestamp:        p.Timestamp,
		Nonce:            p.Nonce,
		EmitterChain:     p.EmitterChain,
		EmitterAddress:   p.EmitterAddress,
		Sequence:         p.Sequence,
		ConsistencyLevel: p.ConsistencyLevel,
		Payload:          payload,
	})
	if err != nil {
		panic(err)
	}
	return vaa
}

func signAccept(key *guardian.Key, p guardian.GovernanceParams, chain uint16, managerAddress [32]byte, factoryEpoch uint64) []byte {
	vaa, err := guardian.SignAcceptAdmin(key, p, chain, managerAddress, factoryEpoch)
	if err != nil {
		panic(err)
	}
	return vaa
}

func main() {
	key, err := guardian.KeyFromHex(devnetGuardianKeyHex)
	if err != nil {
		panic(err)
	}

	type fixture struct {
		name string
		vaa  []byte
	}

	wrongEmitterChainParams := baseParams(7)
	wrongEmitterChainParams.EmitterChain = 2

	wrongEmitterAddressParams := baseParams(8)
	wrongEmitterAddressParams.EmitterAddress = b32(0x05)

	fixtures := []fixture{
		{"happy", signAccept(key, baseParams(1), cantonChain, managerAA, 0)},
		{"wrongModule", signRaw(key, baseParams(2), rawAcceptAdminPayload(coreModulePadded, guardian.AcceptAdminAction, cantonChain, managerAA, 0))},
		{"wrongAction", signRaw(key, baseParams(3), rawAcceptAdminPayload(guardian.NttGovernanceModule, 2, cantonChain, managerAA, 0))},
		{"wrongChain", signAccept(key, baseParams(4), 2, managerAA, 0)},
		{"wrongManager", signAccept(key, baseParams(5), cantonChain, managerAB, 0)},
		{"wrongEpoch", signAccept(key, baseParams(6), cantonChain, managerAA, 1)},
		{"wrongEmitterChain", signAccept(key, wrongEmitterChainParams, cantonChain, managerAA, 0)},
		{"wrongEmitterAddress", signAccept(key, wrongEmitterAddressParams, cantonChain, managerAA, 0)},
	}

	for _, f := range fixtures {
		fmt.Printf("%s = %s\n", f.name, hex.EncodeToString(f.vaa))
	}
}
