# Wormhole addition: the "guardian-governance" Canton participant -- see canton/bob/app.conf
# for the pattern this mirrors.
canton.participants.guardian-governance = ${_participant} {
  storage.config.properties.databaseName = participant-guardian-governance
  monitoring {
    http-health-server.port = 6900
    grpc-health-server.port = 6961
  }
  http-ledger-api.port = 6975
  admin-api.port = 6902
  ledger-api.port = 6901
}
